# Generated by Django 5.1 on 2025-08-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publicationDate', models.DateField()),
                ('blurb', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('contents', models.TextField()),
                ('tags', models.ManyToManyField(related_name='posts', to='blogPosts.tag')),
            ],
        ),
    ]
