# Generated by Django 5.1 on 2025-11-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tumbnailAltText',
            field=models.CharField(default='temp alttext', max_length=250),
            preserve_default=False,
        ),
    ]
